import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TabBar, { TabBarItem } from "@/components/TabBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const tabs = [
  { href: "/home", text: "Home" },
  { href: "/filter", text: "Filter" },
  { href: "/my", text: "My" },
] as TabBarItem[];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <TabBar tabBarItems={tabs}>{children}</TabBar>
      </body>
    </html>
  );
}
